// <auto-generated />
namespace ProductsWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_fk_categories_in_table_Products : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_fk_categories_in_table_Products));
        
        string IMigrationMetadata.Id
        {
            get { return "201804011632248_Add_fk_categories_in_table_Products"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
